try{console.log("Hello Console.")}catch(e$$5){window.console={};for(var cMethods="assert,count,debug,dir,dirxml,error,exception,group,groupCollapsed,groupEnd,info,log,markTimeline,profile,profileEnd,time,timeEnd,trace,warn".split(","),i=0;i<cMethods.length;i++)console[cMethods[i]]=function(){}}
(function(b){window.EaseYouTubePlayer=function(d){var a=this,e={user:"benjrallen",maxResults:8,page:1,playerId:"easeYtPlayer",playerContId:"easeVideoPlayer",thumbsContId:"easeVideoBlocks",loadingMaskId:"easeLoadingMask",thumbBlockClass:"easeThumbBlock",imgContClass:"easeImg",imgLinkClass:"easeImgLink",imgClass:"easeVideoThumb",titleEl:"div",titleClass:"easeThumbTitle",descClass:"easeDesc",playClass:"easePlay",playText:"Play",playerCloseId:"easeClose",playerCloseText:"x",playerMaxHeight:853,playerPercent:0.8,
paginateContId:"easePagin",navClass:"easeNav",navPrevText:"<< Prev",navNextText:"Next >>",localCallUrl:window.location.protocol+"//"+window.location.host+window.location.pathname+"js/videos.php"},c;for(c in d)e[c]=d[c]||e[c];for(c in e)a[c]=e[c];a.CONSTANT="constant";a.API_URL="https://gdata.youtube.com/feeds/api/videos";a.API_USER_UPLOADS="https://gdata.youtube.com/feeds/api/users/"+a.user+"/uploads";a.ALT="jsonc";a.START_INDEX=null;a.TOTAL_ITEMS=null;a.LOADING=!0;a.loadTimeout=null;a.FIRST_LOAD=
!0;a.CURRENT_VIDEO=null;a.player=null;a.showPlayer=!1;a.IS_LTE7=b(".lte7").length;a.IS_LTE8=b(".lte8").length;a.API_READY=!1;a.PLAYER_READY=!1;a.init=function(){a.loadIFrameAPI();a.playerCont=b("#"+a.playerContId);a.thumbsCont=b("#"+a.thumbsContId);if(!a.playerCont.length||!a.thumbsCont.length)return alert("script won't run because video script has no place to put the player or the videos! please provide ids.");a.thumbsCont.addClass("easeVideos");a.updateStartIndex();a.playerClose=b("#"+a.playerCloseId);
if(!a.playerClose.length)a.playerClose=b("<a />",{id:a.playerCloseId,text:a.playerCloseText,title:"Close video"}).insertBefore(a.playerCont);b("body").click(a.onPlayerClose);a.loadingMask=b("#"+a.loadingMaskId);if(!a.loadingMask.length)a.loadingMask=b("<div />",{id:a.loadingMaskId}).prependTo(a.thumbsCont);a.loadingMask.show();b(window).resize(a.positionPlayer);b(document).scroll(a.positionPlayer);return a.getUserVideos()};a.loadIFrameAPI=function(){var a=document.createElement("script");a.src="http://www.youtube.com/player_api";
var b=document.getElementsByTagName("script")[0];b.parentNode.insertBefore(a,b)};a.onYouTubePlayerAPIReady=function(){a.API_READY=!0;return a.loadPlayer()};window.onYouTubePlayerAPIReady=a.onYouTubePlayerAPIReady;a.getUserVideos=function(){var f={alt:a.ALT,"max-results":a.maxResults,"start-index":a.START_INDEX,v:2},h=a.API_USER_UPLOADS;if(a.IS_LTE8)h=a.localCallUrl,f.apiUrl=a.API_USER_UPLOADS;return b.getJSON(h,f,a.printVideoBlocks)};a.printVideoBlocks=function(f,h){a.LOADING=!1;if(h==="success"&&
f.data.items){a.TOTAL_ITEMS=f.data.totalItems;b(".easeCont, #"+a.paginateContId).remove();for(var c=b("<div />",{}).addClass("easeCont").appendTo(a.thumbsCont),d=0,e=f.data.items.length;d<e;d++)a.makeVideoBlock(f.data.items[d]).appendTo(c);f.data.totalItems>a.maxResults&&a.makePagination().insertAfter(a.thumbsCont);a.loadingMask.hide();if(a.FIRST_LOAD)a.FIRST_LOAD=!1,a.CURRENT_VIDEO=f.data.items[0]}};a.loadPlayer=function(){if(!a.API_READY||!a.CURRENT_VIDEO)return a.loadTimeout=setTimeout(a.loadPlayer,
10);var f=a.makePlayerDimensions();a.player=new YT.Player(a.playerContId,{height:f.playerHeight,width:f.playerWidth,videoId:a.CURRENT_VIDEO.id,events:{onReady:a.onPlayerReady}});return a.playerCont=b("#"+a.playerContId)};a.onPlayerReady=function(){a.PLAYER_READY=!0};a.makePlayerDimensions=function(){var f=b(window).width(),c=b(window).height(),d=0,e=0,e=Math.floor(f*a.playerPercent),d=f<c?e:Math.floor(c*a.playerPercent*16/9);d>e&&(d=e);if(d>a.playerMaxHeight)d=a.playerMaxHeight;e=Math.floor(0.5625*
d);return{baseWidth:f,baseHeight:c,playerWidth:d,playerHeight:e}};a.positionPlayer=function(){if(a.player&&a.showPlayer&&a.PLAYER_READY){var b=a.makePlayerDimensions(),c=b.playerWidth,d=Math.floor((b.baseWidth-c)/2),e=Math.floor(b.baseHeight*0.1);a.player.setSize(c,b.playerHeight);a.playerCont.css({left:d,top:e});a.playerClose.css({left:d+c,top:e})}};a.loadVideo=function(){if(a.player&&a.PLAYER_READY)a.showPlayer=!0,a.player.loadVideoById(a.CURRENT_VIDEO.id,0,"large"),a.positionPlayer(),a.player.playVideo()};
a.closePlayer=function(){if(a.player&&a.showPlayer)a.showPlayer=!1,a.player.stopVideo(),a.playerCont.css({left:-1E4}),a.playerClose.css({left:-1E4})};a.makePagination=function(){var f=b("<div />",{id:a.paginateContId});b("<a />",{text:a.navPrevText}).addClass(a.navClass+" prev").click(a.onPaginClick).appendTo(f);b("<a />",{text:a.navNextText}).addClass(a.navClass+" next").click(a.onPaginClick).appendTo(f);b("<span />",{text:"Page "+a.page+" of "+Math.ceil(a.TOTAL_ITEMS/a.maxResults)}).appendTo(f);
b("<div />").addClass("clearfix").appendTo(f);return f};a.makeVideoBlock=function(f){if(!f)return!1;var c=b("<div />",{}).addClass(a.thumbBlockClass).data({itemData:f}).click(a.onBlockPlay);f.thumbnail.sqDefault&&b("<div />",{html:'<a class="'+a.imgLinkClass+'"><img src="'+f.thumbnail.sqDefault+'" class="'+a.imgClass+'" /></a>'}).addClass(a.imgContClass).appendTo(c);f.title&&b("<"+a.titleEl+" />",{html:f.title}).addClass(a.titleClass).appendTo(c);f.description&&b("<div />",{html:f.description}).addClass(a.descClass).appendTo(c);
b("<a />",{text:a.playText}).addClass(a.playClass).appendTo(c);return c};a.onPaginClick=function(){if(!a.LOADING)return b(this).hasClass("next")?a.page===Math.ceil(a.TOTAL_ITEMS/a.maxResults)?a.page=1:a.page++:a.page===1?a.page=Math.ceil(a.TOTAL_ITEMS/a.maxResults):a.page--,a.updateStartIndex(),a.loadingMask.show(),a.LOADING=!0,a.getUserVideos()};a.onPlayerClose=function(b){b.target!==a.player&&a.closePlayer()};a.onBlockPlay=function(f){f.stopPropagation();a.CURRENT_VIDEO=b(this).data("itemData");
return!a.IS_LTE7?a.loadVideo():window.location.href=a.CURRENT_VIDEO.player["default"]};a.updateStartIndex=function(){return a.START_INDEX=(a.page-1)*a.maxResults+1};a.init()}})(jQuery);
(function(b){window.EaseMap=function(d){var a=this,e={zoom:4,centerLat:38.7902935,centerLng:-97.64023729999997,mapHeight:380,minZoom:3,fitMarkers:!1,contId:"gmapCont",dataCont:".distributor-wrap",dataBlock:".distributor",dataAttr:"dist-data",locationKey:"distributor_street_address",fallbackLocationKey:"distributor_mailing_address",zoomControlStyle:"DEFAULT",streetViewControl:!1,scrollwheel:!1,mapTypeId:"ROADMAP",blocksAreClickable:!1,directionsLink:!1,globalInitID:"EaseMapInit"},c;for(c in d)e[c]=
d[c]||e[c];for(c in e)a[c]=e[c];a.loadingGoogle=!1;a.setupConstants=function(){if(typeof google!=="undefined")return window[a.globalInitID]&&(window[a.globalInitID]=void 0),a.loadingGoogle=!1,a.infowindow=new google.maps.InfoWindow,a.directionsService=new google.maps.DirectionsService,a.directionsDisplay=new google.maps.DirectionsRenderer,a.directionsDisplay.setMap(null),a.geocoder=new google.maps.Geocoder,a.startAddy="",a.endAddy="",a.currentRoute=null,a.data=[],a.markers=[],a.init();else if(!a.loadingGoogle){a.loadingGoogle=
!0;window[a.globalInitID]=a.setupConstants;var b=document.createElement("script");b.type="text/javascript";b.src="http://maps.googleapis.com/maps/api/js?sensor=false&callback="+a.globalInitID;document.body.appendChild(b)}};a.init=function(){a.setupMarkerData();a.setupMap();a.setupMarkers()};a.setupMap=function(){a.cont=document.getElementById(a.contId);b(a.cont).height()||b(a.cont).height(a.mapHeight);a.center=new google.maps.LatLng(a.centerLat,a.centerLng);a.map=new google.maps.Map(a.cont,{center:a.center,
zoom:a.zoom,zoomControlOptions:{style:google.maps.ZoomControlStyle[a.zoomControlStyle]},streetViewControl:a.streetViewControl,scrollwheel:a.scrollwheel,mapTypeId:google.maps.MapTypeId[a.mapTypeId]})};a.setupMarkers=function(){if(a.data.length){var f=new google.maps.LatLngBounds;b.each(a.data,function(c){var d=this,e=d[a.locationKey]||d[a.fallbackLocationKey];e&&a.geocoder.geocode({address:a.stripTags(e)},function(e,j){j===google.maps.GeocoderStatus.OK?(a.markers[c]=new google.maps.Marker({map:a.map,
position:e[0].geometry.location,item:d}),google.maps.event.addListener(a.markers[c],"mousedown",a.handleMarkerClick),a.blocksAreClickable&&b(d.DOM).attr({markerIndex:c}).mousedown(a.handleBlockClick).find("a").click(a.preventBlockLinks),a.fitMarkers&&(f.extend(a.markers[c].position),a.map.fitBounds(f))):alert("Geocode was not successful for the following reason: "+j)})})}};a.preventBlockLinks=function(a){a.preventDefault()};a.handleBlockClick=function(){var c=a.markers[b(this).attr("markerIndex")],
d={latLng:c.position};a.map.getZoom()<a.minZoom&&a.map.setZoom(a.minZoom);return a.handleMarkerClick.apply(c,[d])};a.handleMarkerClick=function(){var c='<div class="mapInfoDom">'+b(this.item.DOM).html();if(a.directionsLink){var d="http://maps.google.com/maps?saddr=&daddr="+this.item[a.locationKey].replace(/ /g,"+").replace(/\n/g,",+");c+='<a class="directionsLink" href="'+d+'" title="Get directions to this site" target="_blank">Get Driving Directions</a>'}c+="</div>";a.infowindow.setContent(c);a.infowindow.open(a.map,
this)};a.setupMarkerData=function(){return b(a.dataCont).find(a.dataBlock).each(function(){var c=JSON.parse(b(this).attr(a.dataAttr));c.DOM=this;a.data.push(c)})};a.stripTags=function(a){return typeof a!=="string"?!1:a.replace(/<([^>]+)>/g,"").replace(/\n|\r/g," ")};a.setupConstants();return a}})(jQuery);
(function(b){b.fn.lazyload=function(d){var a={threshold:0,failurelimit:0,event:"scroll",effect:"show",container:window};d&&b.extend(a,d);var e=this;"scroll"==a.event&&b(a.container).bind("scroll",function(){var c=0;e.each(function(){if(!b.abovethetop(this,a)&&!b.leftofbegin(this,a))if(!b.belowthefold(this,a)&&!b.rightoffold(this,a))b(this).trigger("appear");else if(c++>a.failurelimit)return!1});var f=b.grep(e,function(a){return!a.loaded});e=b(f)});this.each(function(){var c=this;void 0==b(c).attr("original")&&
b(c).attr("original",b(c).attr("src"));"scroll"!=a.event||void 0==b(c).attr("src")||a.placeholder==b(c).attr("src")||b.abovethetop(c,a)||b.leftofbegin(c,a)||b.belowthefold(c,a)||b.rightoffold(c,a)?(a.placeholder?b(c).attr("src",a.placeholder):b(c).removeAttr("src"),c.loaded=!1):c.loaded=!0;b(c).one("appear",function(){this.loaded||b("<img />").bind("load",function(){b(c).hide().attr("src",b(c).attr("original"))[a.effect](a.effectspeed);c.loaded=!0}).attr("src",b(c).attr("original"))});"scroll"!=a.event&&
b(c).bind(a.event,function(){c.loaded||b(c).trigger("appear")})});b(a.container).trigger(a.event);return this};b.belowthefold=function(d,a){return(a.container===void 0||a.container===window?b(window).height()+b(window).scrollTop():b(a.container).offset().top+b(a.container).height())<=b(d).offset().top-a.threshold};b.rightoffold=function(d,a){return(a.container===void 0||a.container===window?b(window).width()+b(window).scrollLeft():b(a.container).offset().left+b(a.container).width())<=b(d).offset().left-
a.threshold};b.abovethetop=function(d,a){return(a.container===void 0||a.container===window?b(window).scrollTop():b(a.container).offset().top)>=b(d).offset().top+a.threshold+b(d).height()};b.leftofbegin=function(d,a){return(a.container===void 0||a.container===window?b(window).scrollLeft():b(a.container).offset().left)>=b(d).offset().left+a.threshold+b(d).width()};b.extend(b.expr[":"],{"below-the-fold":"$.belowthefold(a, {threshold : 0, container: window})","above-the-fold":"!$.belowthefold(a, {threshold : 0, container: window})",
"right-of-fold":"$.rightoffold(a, {threshold : 0, container: window})","left-of-fold":"!$.rightoffold(a, {threshold : 0, container: window})"})})(jQuery);
(function(b){window.SyndicatedSubwayTiles=function(d){var a=this,e={url:"http://subwaytiles.bennya.com",wrapId:"content",count:1,speed:15,loadFromBottom:5E3,navEl:"nav#jsui",scrollSpeed:1E3,smoothScroll:!1,placeholderImage:Ease.TemplateUrl+"/images/transparent.gif"},c;for(c in d)e[c]=d[c]||e[c];for(c in e)a[c]=e[c];a.placeholder="";a.page=1;a.getting=!1;a.localUrl=window.location.protocol+"//"+window.location.host+window.location.pathname;a.init=function(){a.placeholder=a.placeholderImage;a.nav=b(a.navEl);
a.navUl=a.nav.find("#posts");a.nav.find("#menuToggle").click(function(){a.navUl.slideToggle(200)});a.wrap=b("#"+a.wrapId).length?b("#"+a.wrapId):b("<div />",{id:a.wrapId}).appendTo("body");a.getPosts();b(a.wrap).parent().scroll(function(){a.getting||b(this).scrollTop()>b(a.wrap).height()-a.loadFromBottom&&a.getPosts()})};a.getPosts=function(){a.getting=!0;var c="?json=get_recent_posts&";a.count>0?c+="count="+a.count+"&":b.noop();c+="page="+a.page;b.getJSON(a.url+c,function(c){c.posts.length&&b.each(c.posts,
a.printPost);a.page+=1})};a.printPost=function(c,d){var e=b("<span />",{id:d.id}).appendTo(a.wrap);b("<a />",{href:"#"+d.id}).html(d.title).appendTo(a.navUl).wrap("<li>").click(a.navClick);a.timeoutPrint(0,e,d)};a.navClick=function(c){if(a.smoothScroll){c.preventDefault();var d=b(this).attr("href"),d=d.substr(1,d.length),c=b(a.wrap).find("#"+d).position(),d=b(a.wrap).find("#"+d).children().first();d.length&&(c=d.position());b(a.wrap).parent().animate({scrollTop:c.top+"px"},a.scrollSpeed);return!1}};
a.timeoutPrint=function(c,d,e){if(c<e.attachments.length){var g=e.attachments[c];if(g.mime_type.indexOf("image")>-1)g=g.images.full,b("<img />",{src:g.url,height:g.height,width:g.width}).appendTo(d).lazyload({placeholder:a.placeholder,effect:"fadeIn",container:a.wrap.parent()});a.timeout=setTimeout(function(){a.timeoutPrint(c+1,d,e)},a.speed)}else clearTimeout(a.timeout),a.getting=!1};a.init();return a}})(jQuery);(function(b){function d(a){if(!a)return!1;var c=b("#header").find("a"),d=!1;b.each(c,function(){if(b(this).text().toLowerCase()==a)return d=b(this),!1});c=null;return d}function a(){var a=d("pictures");if(a)if(Ease.ie)a.attr({href:"http://subwaytiles.bennya.com",target:"_blank"});else{var c=b("#subwayTilesWrap");a.click(function(a){a.preventDefault();g||(g=new SyndicatedSubwayTiles({wrapId:"subwayTiles",smoothScroll:!0}));c.show(250)});b("#closeSubwayTiles").click(function(){c.hide(250)})}a=null}
function e(){if(b("#worksTop").length){var a=b("#worksTop").find("a"),c=b("#header").outerHeight()+b("#worksTop").outerHeight();b("#works").css({marginTop:b("#worksTop").outerHeight()-18});var d=function(a){a.preventDefault();a=b(this).attr("href");a=a.substr(1,a.length);a=b("#"+a).offset();b("html, body").animate({scrollTop:a.top-c+"px"},f)};b.each(a,function(){var a=b(this).attr("href");a&&a.indexOf("#")===0&&b(this).click(d)});a=null;b("#works").find("img").click(function(){b(this).addClass("active").siblings().removeClass("active");
b(this).parent().parent().next().find("img").attr("src",b(this).attr("src"))})}}function c(){b("#header nav").length&&(b("#header nav").each(function(){var a=b(this),c=b(this).find("li");b(window).resize(function(){var d=0;c.each(function(){d+=b(this).width()});var e=Math.floor((h/2-75-k-d)/(c.length-1)-3);a.is("#accessLeft")?c.not(":first").css({marginLeft:e}):c.not(":last").css({marginRight:e})});c.each(function(){b(this).find("a").attr("href")===window.location.href&&b(this).addClass("current-menu-item current_page_item")})}),
b(window).resize())}var f=350,h=900,k=35,g=!1;b(document).ready(function(){b("html.ie").length?Ease.ie=!0:Ease.ie=!1;b("html.lte8").length?Ease.lte8=!0:Ease.lte8=!1;typeof WebKitPoint!=="undefined"?Ease.webkit=!0:Ease.webkit=!1;c();e();b("#videos").length&&new EaseYouTubePlayer({user:"nakedincorners",localCallUrl:Ease.TemplateUrl+"js/videos.php",maxResults:6});b("#locations").length&&new EaseMap({zoom:2,streetViewControl:!0,fitMarkers:!0,centerLat:36.153982,centerLng:-95.992775,dataCont:".locationList",
dataBlock:".locationItem",dataAttr:"ease-data",locationKey:"ba_place_address",directionsLink:!1,blocksAreClickable:!0});if(b("#resumeHref").length){var f=b("#resumeHref").text();b("#header").find("a");var g=d("resume");g&&g.attr({href:f,target:"_blank"})}a()})})(jQuery);var _gaq=_gaq||[];_gaq.push(["_setAccount","UA-28492745-1"]);_gaq.push(["_trackPageview"]);
(function(){var b=document.createElement("script");b.type="text/javascript";b.async=!0;b.src=("https:"==document.location.protocol?"https://ssl":"http://www")+".google-analytics.com/ga.js";var d=document.getElementsByTagName("script")[0];d.parentNode.insertBefore(b,d)})();
